### ISSUE TITLE
Crash when creating results directory

### ISSUE THREAD

**Issue by jmmcd** [jmmcd/PonyGE2#41] opened 2017-02-04 10:58 UTC
```
    # Generate save folders
    if not path.isdir(params['FILE_PATH']):
        mkdir(params['FILE_PATH'])
```

It's a race condition -- if we're running multiple runs at the same time, and the directory doesn't already exist, then several of the runs will reach this `if` and decide they have to make the directory, then get suspended, then one of them will succeed in making it, then the others will crash, because this `mkdir` crashes if its object directory already exists.

Fix: use a different `mkdir` I suppose?

**Comment by jmmcd** [comment] 2017-02-09 14:06
Use `makedirs()`, I think.

Also, we decided to create longer unique dirs per run: `hostname_seed_pid_timestamp`

**Comment by mikefenton** [comment] 2017-02-09 14:07
The longer unique dirs is now in the last few commits. Does makedirs work for you?

**Comment by mikefenton** [comment] 2017-02-09 16:22
Changed `mkdir()` to `makedirs()`. Hopefully this solves this issue.

**Comment by mikefenton** [comment] 2017-02-14 15:25
Can you confirm if this issue has been resolved James?

**Comment by mikefenton** [comment] 2017-03-24 14:21
Closing this issue as we can't replicate the crash any more after code changes. Note that this doesn't necessarily mean the issue is resolved, just that we can't replicate it. Issue can be re-opened if the problem occurs again.

**Closed by mikefenton** 2017-03-24 14:21 UTC
