### ISSUE TITLE
Additional Problems

### ISSUE THREAD

**Issue by dvpfagan** [jmmcd/PonyGE2#3] opened 2016-03-23 14:46 UTC
Hi Guys, so the issue now is what problems do we include with ponyge. Would someone care to add some more problems? Or suggest problems to use. I know a lot of the original problems needs to be added. 

Dave

**Comment by mikefenton** [comment] 2016-09-27 14:45
We currently have String-Match, Regression, and Classification problems implemented. Documentation for the Classification problem needs to be filled out. Dave suggested the addition of a possible Santa-Fe Ant Trail type problem, any ideas?

**Comment by mikefenton** [comment] 2016-10-07 12:22
It has been made easier to add problems to PonyGE. Everything is automated, and there is now probably only one place where you need to add in extra code (apart from adding in the problem itself, obviously). The flipside of this is that you can easily mis-configure PonyGE if you fail to specify everything correctly. _Note that this can be remedied somewhat with the new parameter config files._

**To add in a new problem:**
You simply need to write a **new fitness function** (if you don't want to use one already there) and add a **new grammar file**. You may also need to add a **new dataset** if you're using datasets.

Fitness functions can be specified from the command line with --fitness_function (fitness functions must be a class with the same name as the file containing the class), e.g. fitness.regression.regression. _Note that any regression-style problems that include training and test data will require a **self.training_test = True** attribute in the init function for your fitness function class._

Grammar files can be specified from the command line with --bnf_grammar. When specifying the grammar file you must specify the full file extension, e.g. "Keijzer6.bnf".

Datasets can be specified from the command line with --dataset. When specifying the dataset you _don't_ need to specify the file extension.

Finally, to add in the new problem you may need to edit one or two functions:

1. fitness.fitness_wheel.set_fitness_params (this may be re-named to make it more descriptive/obvious), and/or
2. representation.individual.Individual.evaluate

These functions are the only two remaining "if/else" catch functions in PonyGE. Essentially you specify the inputs needed for initialising your fitness function in set_fitness_params, and you specify the inputs needed for evaluation in individual.evaluate. _Note that it may not be necessary to edit individual.evaluate if you only pass in the phenotype to be evaluated._

**Comment by jmmcd** [comment] 2017-02-08 13:58
Let's add a Max fitness function and a Python pybnf-style grammar, and leave it at that.

**Comment by jmmcd** [comment] 2017-02-09 12:59
No wait! Let's keep going!

I have three more regression datasets which are easy to add.

Stefan will commit his programming problems.

There is also the Tartarus problem, an interesting tiny game, specified here: 

https://pdfs.semanticscholar.org/1819/0433f7652ed3e5c8c361c7c7ca95bfeeb57c.pdf

**Comment by jmmcd** [comment] 2017-02-09 16:14
I've added fitness/pymax.py and grammars/pymax.pybnf, it looks like a fun little variation on the Max problem which could teach us something about programming problems.

Also added three more regression problems -- we have Pagie, V4, K6, Tower, Dow, Housing.

**Comment by mikefenton** [comment] 2017-02-22 15:52
Closing this issue. We have 5 classes of documented problems, not including Stefan's program synthesis problems (which have yet to be documented). If people feel like adding more, please fire away but remember to comment and document everything (including the README).

**Closed by mikefenton** 2017-02-22 15:52 UTC
